# Generated by Django 6.0.7 on 2026-07-26 23:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم وسيلة الدفع')),
                ('method_type', models.CharField(choices=[('card', 'بطاقة بنكية'), ('mada', 'مدى'), ('apple_pay', 'Apple Pay'), ('stc_pay', 'STC Pay'), ('bank_transfer', 'تحويل بنكي'), ('cash_on_delivery', 'الدفع عند الاستلام'), ('other', 'أخرى')], max_length=30, unique=True, verbose_name='نوع وسيلة الدفع')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='payments/methods/', verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'وسيلة دفع',
                'verbose_name_plural': 'وسائل الدفع',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم العملية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('processing', 'قيد المعالجة'), ('paid', 'مدفوع'), ('failed', 'فشل الدفع'), ('cancelled', 'ملغي'), ('partially_refunded', 'مسترد جزئيًا'), ('refunded', 'مسترد بالكامل')], db_index=True, default='pending', max_length=30, verbose_name='حالة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('gateway_reference', models.CharField(blank=True, db_index=True, max_length=250, verbose_name='مرجع بوابة الدفع')),
                ('gateway_name', models.CharField(blank=True, max_length=100, verbose_name='اسم بوابة الدفع')),
                ('failure_reason', models.TextField(blank=True, verbose_name='سبب فشل الدفع')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء العملية')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='الطلب')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentmethod', verbose_name='وسيلة الدفع')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'عمليات الدفع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم الاسترداد')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ المسترد')),
                ('reason', models.TextField(verbose_name='سبب الاسترداد')),
                ('status', models.CharField(choices=[('requested', 'تم طلب الاسترداد'), ('processing', 'قيد المعالجة'), ('completed', 'مكتمل'), ('rejected', 'مرفوض'), ('failed', 'فشل')], db_index=True, default='requested', max_length=30, verbose_name='حالة الاسترداد')),
                ('gateway_reference', models.CharField(blank=True, max_length=250, verbose_name='مرجع بوابة الدفع')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اكتمال الاسترداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment', verbose_name='عملية الدفع')),
            ],
            options={
                'verbose_name': 'عملية استرداد',
                'verbose_name_plural': 'عمليات الاسترداد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['order', 'status'], name='payments_pa_order_i_a76289_idx'),
        ),
    ]
