# Generated by Django 6.0.7 on 2026-07-26 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('subtitle', models.CharField(blank=True, max_length=250, verbose_name='العنوان الفرعي')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='صورة الإعلان')),
                ('button_text', models.CharField(blank=True, max_length=100, verbose_name='نص الزر')),
                ('button_url', models.CharField(blank=True, help_text='يمكن إدخال رابط داخلي أو رابط خارجي آمن.', max_length=500, verbose_name='رابط الزر')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='بداية العرض')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع الرسالة')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
            options={
                'verbose_name': 'رسالة تواصل',
                'verbose_name_plural': 'رسائل التواصل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=200, verbose_name='اسم المتجر')),
                ('site_description', models.TextField(blank=True, verbose_name='وصف المتجر')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logos/', verbose_name='شعار المتجر')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/favicon/', verbose_name='أيقونة الموقع')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='رقم واتساب')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('currency', models.CharField(default='SAR', max_length=10, verbose_name='العملة')),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=15, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='نسبة الضريبة')),
                ('is_maintenance_mode', models.BooleanField(default=False, verbose_name='وضع الصيانة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات المتجر',
                'verbose_name_plural': 'إعدادات المتجر',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الصفحة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='الرابط المختصر')),
                ('content', models.TextField(verbose_name='محتوى الصفحة')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='وصف محركات البحث')),
                ('is_active', models.BooleanField(default=True, verbose_name='منشورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'صفحة ثابتة',
                'verbose_name_plural': 'الصفحات الثابتة',
                'ordering': ['title'],
            },
        ),
    ]
