# Generated by Django 6.0.7 on 2026-08-05 22:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_acidity_product_altitude_masl_and_more'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrewTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='اسم الأداة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='الرابط المختصر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
            ],
            options={
                'verbose_name': 'أداة تحضير',
                'verbose_name_plural': 'أدوات التحضير',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(allow_unicode=True, max_length=170, unique=True, verbose_name='الرابط المختصر')),
                ('content_type', models.CharField(choices=[('encyclopedia', 'الموسوعة'), ('academy', 'الأكاديمية'), ('term', 'المصطلحات')], db_index=True, max_length=20, verbose_name='نوع المحتوى')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تصنيف معرفي',
                'verbose_name_plural': 'تصنيفات الموسوعة والأكاديمية',
                'ordering': ['content_type', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BrewMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='الاسم')),
                ('slug', models.SlugField(allow_unicode=True, max_length=170, unique=True, verbose_name='الرابط المختصر')),
                ('short_description', models.CharField(max_length=350, verbose_name='وصف مختصر')),
                ('description', models.TextField(verbose_name='وصف تفصيلي')),
                ('image', models.ImageField(blank=True, upload_to='brew/methods/', verbose_name='الصورة الرئيسية')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('advanced', 'متقدم')], db_index=True, max_length=20, verbose_name='مستوى الصعوبة')),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='الوقت المتوقع بالدقائق')),
                ('coffee_grams', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(1)], verbose_name='كمية البن (جرام)')),
                ('water_ml', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='كمية الماء (مل)')),
                ('ratio', models.CharField(max_length=30, verbose_name='نسبة البن إلى الماء')),
                ('grind_size', models.CharField(max_length=120, verbose_name='درجة الطحن')),
                ('water_temperature', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='درجة حرارة الماء')),
                ('common_mistakes', models.TextField(blank=True, verbose_name='أخطاء شائعة')),
                ('tips', models.TextField(blank=True, verbose_name='نصائح تحسين النتيجة')),
                ('video_url', models.URLField(blank=True, verbose_name='رابط فيديو اختياري')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منشورة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='وصف SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('products', models.ManyToManyField(blank=True, related_name='brew_methods', to='catalog.product', verbose_name='المنتجات المناسبة')),
                ('tools', models.ManyToManyField(blank=True, related_name='brew_methods', to='core.brewtool', verbose_name='الأدوات المطلوبة')),
            ],
            options={
                'verbose_name': 'طريقة تحضير',
                'verbose_name_plural': 'طرق التحضير',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='العنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='الرابط المختصر')),
                ('summary', models.CharField(max_length=400, verbose_name='الملخص')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('image', models.ImageField(blank=True, upload_to='content/', verbose_name='الصورة الرئيسية')),
                ('difficulty', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], db_index=True, default='beginner', max_length=20, verbose_name='المستوى')),
                ('duration_minutes', models.PositiveIntegerField(default=5, verbose_name='مدة القراءة أو التعلم')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='منشور')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO')),
                ('meta_description', models.CharField(blank=True, max_length=320, verbose_name='وصف SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('products', models.ManyToManyField(blank=True, related_name='coffee_contents', to='catalog.product', verbose_name='منتجات مرتبطة')),
                ('related_contents', models.ManyToManyField(blank=True, to='core.coffeecontent', verbose_name='محتوى مرتبط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='core.contentcategory', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'مقال أو درس',
                'verbose_name_plural': 'الموسوعة والأكاديمية',
                'ordering': ['display_order', '-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BrewStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='الترتيب')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان الخطوة')),
                ('description', models.TextField(verbose_name='شرح الخطوة')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة بالثواني')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.brewmethod', verbose_name='طريقة التحضير')),
            ],
            options={
                'verbose_name': 'خطوة تحضير',
                'verbose_name_plural': 'خطوات التحضير',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('method', 'order'), name='unique_brew_step_order')],
            },
        ),
        migrations.AddIndex(
            model_name='brewmethod',
            index=models.Index(fields=['is_published', 'difficulty', 'display_order'], name='brew_publish_filter_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeecontent',
            index=models.Index(fields=['is_published', 'published_at'], name='content_publish_date_idx'),
        ),
    ]
