# Generated by Django 6.0.7 on 2026-07-26 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('other', 'إجراء آخر')], max_length=20, verbose_name='نوع الإجراء')),
                ('app_label', models.CharField(blank=True, max_length=100, verbose_name='اسم التطبيق')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='اسم النموذج')),
                ('object_id', models.CharField(blank=True, max_length=100, verbose_name='معرف العنصر')),
                ('object_repr', models.CharField(blank=True, max_length=250, verbose_name='وصف العنصر')),
                ('description', models.TextField(blank=True, verbose_name='تفاصيل الإجراء')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإجراء')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل نشاط إداري',
                'verbose_name_plural': 'سجلات النشاط الإداري',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='dashboard_a_action_8ece40_idx'), models.Index(fields=['app_label', 'model_name'], name='dashboard_a_app_lab_86cfe5_idx')],
            },
        ),
    ]
