# Generated by Django 6.0.7 on 2026-08-05 22:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0002_product_acidity_product_altitude_masl_and_more'),
        ('core', '0002_brewtool_contentcategory_brewmethod_coffeecontent_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_product_name', models.CharField(blank=True, max_length=220, verbose_name='اسم منتج خارجي')),
                ('experienced_at', models.DateTimeField(verbose_name='تاريخ التجربة')),
                ('coffee_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='كمية البن')),
                ('water_ml', models.PositiveIntegerField(blank=True, null=True, verbose_name='كمية الماء')),
                ('ratio', models.CharField(blank=True, max_length=30, verbose_name='نسبة التحضير')),
                ('grind_size', models.CharField(blank=True, max_length=120, verbose_name='درجة الطحن')),
                ('water_temperature', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='درجة حرارة الماء')),
                ('extraction_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الاستخلاص')),
                ('overall_rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم العام')),
                ('acidity_rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الحموضة')),
                ('sweetness_rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الحلاوة')),
                ('body_rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='القوام')),
                ('flavor_rating', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='النكهة')),
                ('notes', models.TextField(blank=True, verbose_name='الملاحظات')),
                ('recipe', models.TextField(blank=True, verbose_name='وصفة التحضير')),
                ('image', models.ImageField(blank=True, upload_to='journal/', verbose_name='صورة')),
                ('privacy', models.CharField(choices=[('private', 'خاص'), ('public', 'عام')], db_index=True, default='private', max_length=10, verbose_name='الخصوصية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'تجربة قهوة',
                'verbose_name_plural': 'سجل القهوة الشخصي',
                'ordering': ['-experienced_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, editable=False, verbose_name='الرصيد')),
                ('lifetime_earned', models.PositiveIntegerField(default=0, editable=False, verbose_name='إجمالي المكتسب')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'حساب ولاء',
                'verbose_name_plural': 'حسابات الولاء',
            },
        ),
        migrations.CreateModel(
            name='LoyaltySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='النظام مفعل')),
                ('points_per_riyal', models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='نقاط لكل ريال')),
                ('bronze_min', models.PositiveIntegerField(default=0, verbose_name='حد البرونزي')),
                ('silver_min', models.PositiveIntegerField(default=500, verbose_name='حد الفضي')),
                ('gold_min', models.PositiveIntegerField(default=1500, verbose_name='حد الذهبي')),
                ('platinum_min', models.PositiveIntegerField(default=4000, verbose_name='حد البلاتيني')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الولاء',
                'verbose_name_plural': 'إعدادات الولاء',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'اكتساب'), ('redeem', 'استخدام'), ('reverse', 'عكس'), ('expire', 'انتهاء')], max_length=12, verbose_name='نوع الحركة')),
                ('points', models.IntegerField(verbose_name='النقاط')),
                ('description', models.CharField(max_length=250, verbose_name='البيان')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تنتهي في')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
            ],
            options={
                'verbose_name': 'حركة نقاط',
                'verbose_name_plural': 'حركات النقاط',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('recipe', models.TextField(verbose_name='الوصفة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحفظ')),
            ],
            options={
                'verbose_name': 'وصفة محفوظة',
                'verbose_name_plural': 'الوصفات المحفوظة',
            },
        ),
        migrations.CreateModel(
            name='TasteAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=180, verbose_name='الإجابة')),
                ('value', models.CharField(max_length=80, verbose_name='القيمة')),
                ('score_tags', models.CharField(blank=True, max_length=250, verbose_name='وسوم المطابقة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'إجابة اختبار الذوق',
                'verbose_name_plural': 'إجابات اختبار الذوق',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=120, verbose_name='اسم ملف الذوق')),
                ('preferences', models.JSONField(default=dict, verbose_name='التفضيلات')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'ملف ذوق',
                'verbose_name_plural': 'ملفات الذوق',
            },
        ),
        migrations.CreateModel(
            name='TasteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='السؤال')),
                ('key', models.SlugField(max_length=80, unique=True, verbose_name='المعرف')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'سؤال اختبار الذوق',
                'verbose_name_plural': 'أسئلة اختبار الذوق',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at'], 'verbose_name': 'العنوان', 'verbose_name_plural': 'العناوين'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created_at'], 'verbose_name': 'الملف الشخصي', 'verbose_name_plural': 'الملفات الشخصية'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at'], 'verbose_name': 'قائمة المفضلة', 'verbose_name_plural': 'قوائم المفضلة'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'منتج في قائمة المفضلة', 'verbose_name_plural': 'منتجات قوائم المفضلة'},
        ),
        migrations.AlterField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إضافة العنوان'),
        ),
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='هل هو العنوان الافتراضي؟'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=200, verbose_name='اسم الشارع'),
        ),
        migrations.AlterField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_phone_verified',
            field=models.BooleanField(default=False, verbose_name='هل رقم الهاتف موثق؟'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء قائمة المفضلة'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إضافة المنتج'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', 'is_default'], name='address_user_default_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='address_city_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['wishlist', 'created_at'], name='wishlist_created_idx'),
        ),
        migrations.AddField(
            model_name='coffeejournalentry',
            name='brew_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.brewmethod', verbose_name='طريقة التحضير'),
        ),
        migrations.AddField(
            model_name='coffeejournalentry',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='catalog.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='coffeejournalentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='loyaltyaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_account', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.loyaltyaccount', verbose_name='الحساب'),
        ),
        migrations.AddField(
            model_name='loyaltytransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_transactions', to='orders.order', verbose_name='الطلب'),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='source_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipe', to='accounts.coffeejournalentry', verbose_name='التجربة الأصلية'),
        ),
        migrations.AddField(
            model_name='savedrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='tasteprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AddField(
            model_name='tasteanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='accounts.tastequestion', verbose_name='السؤال'),
        ),
        migrations.AddIndex(
            model_name='coffeejournalentry',
            index=models.Index(fields=['user', 'experienced_at'], name='journal_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeejournalentry',
            index=models.Index(fields=['user', 'overall_rating'], name='journal_user_rating_idx'),
        ),
        migrations.AddConstraint(
            model_name='coffeejournalentry',
            constraint=models.CheckConstraint(condition=models.Q(('product__isnull', False), models.Q(('external_product_name', ''), _negated=True), _connector='OR'), name='journal_requires_product_name'),
        ),
        migrations.AddConstraint(
            model_name='loyaltytransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('order', 'transaction_type'), name='unique_loyalty_order_type'),
        ),
        migrations.AddConstraint(
            model_name='tasteanswer',
            constraint=models.UniqueConstraint(fields=('question', 'value'), name='unique_taste_answer_value'),
        ),
    ]
