# Generated by Django 6.0.7 on 2026-08-05 22:43

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='acidity',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الحموضة'),
        ),
        migrations.AddField(
            model_name='product',
            name='altitude_masl',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='الارتفاع عن سطح البحر (م)'),
        ),
        migrations.AddField(
            model_name='product',
            name='bitterness',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='المرارة'),
        ),
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='القوام'),
        ),
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='الدولة'),
        ),
        migrations.AddField(
            model_name='product',
            name='farm',
            field=models.CharField(blank=True, max_length=180, verbose_name='المزرعة'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_notes',
            field=models.CharField(blank=True, max_length=350, verbose_name='الإيحاءات والنكهات'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True, verbose_name='منشور'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='وصف SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='processing_method',
            field=models.CharField(blank=True, choices=[('washed', 'مغسولة'), ('natural', 'مجففة'), ('honey', 'عسلية'), ('other', 'أخرى')], db_index=True, max_length=30, verbose_name='طريقة المعالجة'),
        ),
        migrations.AddField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, max_length=180, verbose_name='المنتج أو المزارع'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=150, verbose_name='المنطقة'),
        ),
        migrations.AddField(
            model_name='product',
            name='roast_batch_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='رقم دفعة التحميص'),
        ),
        migrations.AddField(
            model_name='product',
            name='roast_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التحميص'),
        ),
        migrations.AddField(
            model_name='product',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('light', 'فاتح'), ('medium', 'متوسط'), ('dark', 'غامق')], db_index=True, max_length=20, verbose_name='درجة التحميص'),
        ),
        migrations.AddField(
            model_name='product',
            name='suitable_brew_methods',
            field=models.CharField(blank=True, max_length=350, verbose_name='طرق التحضير المناسبة'),
        ),
        migrations.AddField(
            model_name='product',
            name='sweetness',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الحلاوة'),
        ),
        migrations.AddField(
            model_name='product',
            name='variety',
            field=models.CharField(blank=True, db_index=True, max_length=180, verbose_name='السلالة'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='acidity_rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الحموضة'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='aroma_rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الرائحة'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='body_rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='القوام'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_verified_purchase',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name='مشتري موثق'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الجودة'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='sweetness_rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='الحلاوة'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='value_rating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='القيمة مقابل السعر'),
        ),
        migrations.AddField(
            model_name='productreview',
            name='would_buy_again',
            field=models.BooleanField(default=False, verbose_name='سيشتريه مرة أخرى'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='شعار العلامة التجارية'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة التصنيف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='صورة المتغير'),
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='الصورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.productreview', verbose_name='المراجعة')),
            ],
            options={
                'verbose_name': 'صورة مراجعة',
                'verbose_name_plural': 'صور المراجعات',
            },
        ),
    ]
