# Generated by Django 6.0.7 on 2026-08-05 22:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_coffeejournalentry_loyaltyaccount_loyaltysetting_and_more'),
        ('catalog', '0002_product_acidity_product_altitude_masl_and_more'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='اسم الخطة')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='السعر')),
                ('duration_months', models.PositiveIntegerField(default=1, verbose_name='مدة الاشتراك بالأشهر')),
                ('frequency', models.CharField(choices=[('monthly', 'شهري'), ('periodic', 'دوري')], default='monthly', max_length=15, verbose_name='التكرار')),
                ('interval_days', models.PositiveIntegerField(default=30, verbose_name='الفاصل بالأيام')),
                ('product_count', models.PositiveIntegerField(default=1, verbose_name='عدد المنتجات')),
                ('weight_grams', models.PositiveIntegerField(default=250, verbose_name='الوزن بالجرام')),
                ('benefits', models.TextField(blank=True, verbose_name='المزايا')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='متاحة')),
                ('max_subscribers', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للمشتركين')),
                ('image', models.ImageField(blank=True, upload_to='subscriptions/plans/', verbose_name='الصورة')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ترتيب الظهور')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('next_shipment_at', models.DateTimeField(db_index=True, verbose_name='موعد الشحنة القادمة')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التفعيل'), ('active', 'نشط'), ('paused', 'متوقف مؤقتًا'), ('cancelled', 'ملغي'), ('expired', 'منتهي')], db_index=True, default='pending', max_length=15, verbose_name='الحالة')),
                ('coffee_preferences', models.TextField(blank=True, verbose_name='تفضيلات القهوة')),
                ('grind_type', models.CharField(choices=[('whole', 'حبوب كاملة'), ('fine', 'ناعم'), ('medium', 'متوسط'), ('coarse', 'خشن')], default='whole', max_length=15, verbose_name='طريقة الطحن')),
                ('paused_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإيقاف')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='accounts.address', verbose_name='العنوان')),
                ('excluded_products', models.ManyToManyField(blank=True, related_name='excluded_from_subscriptions', to='catalog.product', verbose_name='المنتجات المستبعدة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='orders.subscriptionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('scheduled_at', models.DateTimeField(verbose_name='موعد الشحن')),
                ('status', models.CharField(choices=[('scheduled', 'مجدولة'), ('prepared', 'مجهزة'), ('shipped', 'مشحونة'), ('delivered', 'مسلّمة'), ('cancelled', 'ملغاة')], default='scheduled', max_length=15, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_box', to='orders.order', verbose_name='الطلب')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boxes', to='orders.subscription', verbose_name='الاشتراك')),
            ],
            options={
                'verbose_name': 'صندوق اشتراك',
                'verbose_name_plural': 'صناديق الاشتراك',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionBoxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='الكمية')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.subscriptionbox', verbose_name='الصندوق')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_box_items', to='catalog.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'منتج صندوق',
                'verbose_name_plural': 'منتجات الصناديق',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionbox',
            constraint=models.UniqueConstraint(fields=('subscription', 'period_start'), name='unique_subscription_period_box'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionboxitem',
            constraint=models.UniqueConstraint(fields=('box', 'product'), name='unique_product_per_box'),
        ),
    ]
